import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useVMSAuth } from '../../context/VMSAuthContext'
import { gatepassesApi, visitorsApi } from '../../services/vmsApi'
import {
  ArrowLeft,
  User,
  Phone,
  Mail,
  Building,
  Calendar,
  FileText,
  Clock,
  CheckCircle,
  XCircle,
  AlertTriangle,
  Share2,
  Car,
  BadgeCheck,
  Copy,
  Loader2,
  QrCode,
  Users,
} from 'lucide-react'

const VisitorDetail = () => {
  const { id } = useParams()
  const navigate = useNavigate()
  const { isAdmin, isReceptionist } = useVMSAuth()
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  useEffect(() => {
    fetchData()
  }, [id])

  const fetchData = async () => {
    try {
      setLoading(true)
      setError(null)
      
      // Try to fetch as gatepass first
      try {
        const response = await gatepassesApi.getById(id)
        if (response.data) {
          setData({
            type: 'gatepass',
            ...response.data,
            visitor: response.data.visitor || {}
          })
          return
        }
      } catch (err) {
        console.log('Not a gatepass, trying visitor...')
      }
      
      // Try to fetch as visitor
      try {
        const response = await visitorsApi.getById(id)
        if (response.data) {
          setData({
            type: 'visitor',
            visitor: response.data,
            ...response.data.gatepass
          })
          return
        }
      } catch (err) {
        console.log('Not a visitor either')
      }
      
      setError('Record not found')
    } catch (error) {
      console.error('Failed to fetch:', error)
      setError('Failed to load details')
    } finally {
      setLoading(false)
    }
  }

  const formatDateTime = (date) => {
    if (!date) return '-'
    return new Date(date).toLocaleString('en-IN', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      hour12: true
    })
  }

  const getStatusBadge = (status) => {
    const statusConfig = {
      'ACTIVE': { bg: 'bg-green-100', text: 'text-green-700', icon: CheckCircle },
      'CHECKED_IN': { bg: 'bg-green-100', text: 'text-green-700', icon: CheckCircle },
      'CHECKED_OUT': { bg: 'bg-gray-100', text: 'text-gray-700', icon: CheckCircle },
      'USED': { bg: 'bg-blue-100', text: 'text-blue-700', icon: BadgeCheck },
      'EXPIRED': { bg: 'bg-red-100', text: 'text-red-700', icon: XCircle },
      'CANCELLED': { bg: 'bg-red-100', text: 'text-red-700', icon: XCircle },
      'PENDING': { bg: 'bg-yellow-100', text: 'text-yellow-700', icon: AlertTriangle },
      'PENDING_APPROVAL': { bg: 'bg-yellow-100', text: 'text-yellow-700', icon: AlertTriangle },
      'APPROVED': { bg: 'bg-green-100', text: 'text-green-700', icon: CheckCircle },
      'REJECTED': { bg: 'bg-red-100', text: 'text-red-700', icon: XCircle },
    }
    const config = statusConfig[status] || { bg: 'bg-gray-100', text: 'text-gray-700', icon: AlertTriangle }
    const Icon = config.icon
    return (
      <span className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-sm font-medium ${config.bg} ${config.text}`}>
        <Icon size={16} />
        {status?.replace(/_/g, ' ')}
      </span>
    )
  }

  const handleShare = () => {
    const visitor = data?.visitor || data
    const text = `Visitor Pass Details

Name: ${visitor?.visitorName || '-'}
Phone: ${visitor?.phone || '-'}
Company: ${visitor?.companyToVisit || visitor?.companyFrom || '-'}
Purpose: ${visitor?.purpose || '-'}
Pass Number: ${data?.gatepassNumber || '-'}
Status: ${data?.status || visitor?.status || '-'}
Valid Until: ${formatDateTime(data?.validUntil)}

Generated by VMS`

    const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(text)}`
    window.open(whatsappUrl, '_blank')
  }

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text)
    alert('Copied to clipboard!')
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <Loader2 className="w-12 h-12 text-teal-600 animate-spin mx-auto mb-4" />
          <p className="text-gray-600">Loading details...</p>
        </div>
      </div>
    )
  }

  if (error || !data) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <XCircle className="w-16 h-16 text-red-400 mx-auto mb-4" />
          <h2 className="text-xl font-bold text-gray-800 mb-2">Not Found</h2>
          <p className="text-gray-600 mb-4">{error || 'Record not found'}</p>
          <button
            onClick={() => navigate(-1)}
            className="px-4 py-2 bg-teal-600 text-white rounded-lg hover:bg-teal-700"
          >
            Go Back
          </button>
        </div>
      </div>
    )
  }

  const visitor = data.visitor || data

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <button
                onClick={() => navigate(-1)}
                className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
              >
                <ArrowLeft size={20} className="text-gray-600" />
              </button>
              <div>
                <h1 className="text-xl font-bold text-gray-800">Visitor Details</h1>
                <p className="text-sm text-gray-500">
                  {data.gatepassNumber || visitor?.requestNumber || 'View visitor information'}
                </p>
              </div>
            </div>
            <button
              onClick={handleShare}
              className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700"
            >
              <Share2 size={18} />
              Share
            </button>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto p-4 space-y-6">
        {/* Status Card */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="w-20 h-20 bg-gray-100 rounded-full flex items-center justify-center overflow-hidden">
                {visitor?.photo ? (
                  <img src={visitor.photo} alt="" className="w-full h-full object-cover" />
                ) : (
                  <User size={32} className="text-gray-400" />
                )}
              </div>
              <div>
                <h2 className="text-2xl font-bold text-gray-800">{visitor?.visitorName || '-'}</h2>
                <p className="text-gray-500">{visitor?.companyFrom || visitor?.companyToVisit || '-'}</p>
              </div>
            </div>
            {getStatusBadge(data.status || visitor?.status)}
          </div>
        </div>

        {/* Pass Information */}
        {data.gatepassNumber && (
          <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
            <h3 className="text-lg font-semibold text-gray-800 mb-4 flex items-center gap-2">
              <BadgeCheck size={20} className="text-teal-600" />
              Pass Information
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="p-3 bg-gray-50 rounded-lg">
                <p className="text-xs text-gray-500 mb-1">Pass Number</p>
                <div className="flex items-center gap-2">
                  <p className="font-mono font-bold text-gray-800">{data.gatepassNumber}</p>
                  <button
                    onClick={() => copyToClipboard(data.gatepassNumber)}
                    className="p-1 hover:bg-gray-200 rounded"
                  >
                    <Copy size={14} className="text-gray-400" />
                  </button>
                </div>
              </div>
              <div className="p-3 bg-gray-50 rounded-lg">
                <p className="text-xs text-gray-500 mb-1">Valid Until</p>
                <p className="font-medium text-gray-800">{formatDateTime(data.validUntil)}</p>
              </div>
            </div>
          </div>
        )}

        {/* Visitor Details */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
          <h3 className="text-lg font-semibold text-gray-800 mb-4 flex items-center gap-2">
            <User size={20} className="text-teal-600" />
            Visitor Information
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="flex items-center gap-3 p-3 bg-gray-50 rounded-lg">
              <Phone size={18} className="text-gray-400" />
              <div>
                <p className="text-xs text-gray-500">Phone</p>
                <p className="font-medium text-gray-800">{visitor?.phone || '-'}</p>
              </div>
            </div>
            <div className="flex items-center gap-3 p-3 bg-gray-50 rounded-lg">
              <Mail size={18} className="text-gray-400" />
              <div>
                <p className="text-xs text-gray-500">Email</p>
                <p className="font-medium text-gray-800">{visitor?.email || '-'}</p>
              </div>
            </div>
            <div className="flex items-center gap-3 p-3 bg-gray-50 rounded-lg">
              <Building size={18} className="text-gray-400" />
              <div>
                <p className="text-xs text-gray-500">Company To Visit</p>
                <p className="font-medium text-gray-800">{visitor?.companyToVisit || '-'}</p>
              </div>
            </div>
            <div className="flex items-center gap-3 p-3 bg-gray-50 rounded-lg">
              <Users size={18} className="text-gray-400" />
              <div>
                <p className="text-xs text-gray-500">Person To Meet</p>
                <p className="font-medium text-gray-800">{visitor?.personToMeet || '-'}</p>
              </div>
            </div>
            <div className="flex items-center gap-3 p-3 bg-teal-50 rounded-lg col-span-full">
              <FileText size={18} className="text-teal-600" />
              <div>
                <p className="text-xs text-teal-600">Purpose of Visit</p>
                <p className="font-medium text-gray-800">{visitor?.purpose || '-'}</p>
              </div>
            </div>
            {/* Vehicle Number - Always displayed */}
            <div className="flex items-center gap-3 p-3 bg-purple-50 rounded-lg col-span-full">
              <Car size={18} className="text-purple-600" />
              <div>
                <p className="text-xs text-purple-600 font-medium">Vehicle Number</p>
                <p className="font-medium text-gray-800">{visitor?.vehicleNumber || '-'}</p>
              </div>
            </div>
          </div>
        </div>

        {/* Timing Information */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
          <h3 className="text-lg font-semibold text-gray-800 mb-4 flex items-center gap-2">
            <Clock size={20} className="text-teal-600" />
            Timing Information
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="p-3 bg-gray-50 rounded-lg">
              <p className="text-xs text-gray-500 mb-1">Check-in Time</p>
              <p className="font-medium text-gray-800">{formatDateTime(visitor?.checkInTime)}</p>
            </div>
            <div className="p-3 bg-gray-50 rounded-lg">
              <p className="text-xs text-gray-500 mb-1">Check-out Time</p>
              <p className="font-medium text-gray-800">{formatDateTime(visitor?.checkOutTime)}</p>
            </div>
            <div className="p-3 bg-gray-50 rounded-lg">
              <p className="text-xs text-gray-500 mb-1">Entry Type</p>
              <p className="font-medium text-gray-800">{visitor?.entryType?.replace(/_/g, ' ') || '-'}</p>
            </div>
            <div className="p-3 bg-gray-50 rounded-lg">
              <p className="text-xs text-gray-500 mb-1">Number of Visitors</p>
              <p className="font-medium text-gray-800">{visitor?.numberOfVisitors || 1}</p>
            </div>
          </div>
        </div>

        {/* ID Document */}
        {(visitor?.idProofType || visitor?.idDocumentImage) && (
          <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
            <h3 className="text-lg font-semibold text-gray-800 mb-4 flex items-center gap-2">
              <FileText size={20} className="text-teal-600" />
              ID Proof
            </h3>
            <div className="space-y-4">
              {visitor?.idProofType && (
                <div className="p-3 bg-gray-50 rounded-lg">
                  <p className="text-xs text-gray-500 mb-1">ID Type & Number</p>
                  <p className="font-medium text-gray-800">
                    {visitor.idProofType.replace(/_/g, ' ')}: {visitor.idProofNumber || '-'}
                  </p>
                </div>
              )}
              {visitor?.idDocumentImage && (
                <div className="p-3 bg-gray-50 rounded-lg">
                  <p className="text-xs text-gray-500 mb-2">ID Document Image</p>
                  <img 
                    src={visitor.idDocumentImage} 
                    alt="ID Document" 
                    className="max-w-full max-h-64 object-contain rounded-lg border border-gray-200"
                  />
                </div>
              )}
            </div>
          </div>
        )}

        {/* Remarks */}
        {visitor?.remarks && (
          <div className="bg-amber-50 border-2 border-amber-300 rounded-xl p-6">
            <h3 className="text-lg font-semibold text-amber-800 mb-2 flex items-center gap-2">
              <AlertTriangle size={20} className="text-amber-600" />
              REMARKS
            </h3>
            <p className="text-amber-900">{visitor.remarks}</p>
          </div>
        )}
      </div>
    </div>
  )
}

export default VisitorDetail
